version: '3'

services:
    app:
        container_name: bundelt_api
        build: .
        ports:
            - 13000:13000
        environment: 
            PORT: 13000
            DBNAME: "bundelt"
            DBUSER: "bd_user"
            DBPASSWORD: "password"
            DBHOST: "host.docker.internal"
            MASTERMAXCONN: "10"
            MASTERMAXIDLE: "10"
            SLAVEMAXCONN: "10"
            SLAVEMAXIDLE: "10"
            DBPORT: "5432"
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    db:
        image: postgres
        container_name: bundelt_db
        restart: always
        ports:
            - 5432:5432
        environment: 
            POSTGRES_DB: "bundelt"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes: 
            #remove comment to make db data persistent
            #- ./db/postgres-data:/var/lib/postgresql/data
            - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - ./db/sql/create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
 
